### PR TITLE
Handle disconnect of WALT better

### LINKED ISSUE #20: Crash when returning to the app after disconnecting WALT
If the WALT app opened due to the device being connected, then opened again in such a way that no new intent is created (such as from the recents menu), the app will request permission to access a (nonexistent) USB device. If "OK" is chosen, a crash occurs.

### PR DESCRIPTION
**Pull request by BenjaminFair**
Improvements to handling the WALT device being disconnected, including proper results from isConnected() and avoiding a crash

Fixes #20

### CODE REVIEW

File: android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java [hunk 1]
```diff
@@ -91,6 +91,7 @@ protected void onResume() {
         final UsbDevice usbDevice;
         Intent intent = getIntent();
         if (intent != null && intent.getAction().equals(UsbManager.ACTION_USB_DEVICE_ATTACHED)) {
+            setIntent(null); // done with the intent
```
Comment (kamrik) [inline android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java]: Is this the correct order, first setIntent and the get the device out of the saved intent? Feels a bit weird.

Comment (BenjaminFair) [inline android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java]: getInent() and setIntent() interact with the last intent which caused the app to open. I'm getting a local reference to the intent and then clearing it from the system so that if onResume is triggered, but there is no new intent (such as when the screen is turned off and back on) it won't try to act based on the old intent.

**Comment by kamrik** [comment]
Looks good. Merging. 
Thanks.

**Comment by gkasten** [comment]
+1
